FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /service

COPY requirements.txt /service/requirements.txt
RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir -r /service/requirements.txt

COPY . /service
RUN chmod +x /service/entrypoint.sh

CMD ["/service/entrypoint.sh"]
